
stages:
  - setup

setup:
  stage: setup
  image: alpine:latest
  script:
    - echo "exporting variables..."
    - export $(grep -v '^#' .env.example | xargs)
    - echo "variable db_url is : $DB_URL"





image: docker:27

services:
  - docker:27-dind

variables:
  IMAGE_NAME: delivery-backend
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

stages:
  - build
  - push

build_images:
  stage: build
  script:
    - docker build -t "$DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG" .
    - docker save "$DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG" > image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 20 minutes


deploy_to_hub:
  stage: push
  script:
    - docker load < image.tar
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    - docker push "$DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG"

