stages:
  - setup

setup:
  stage: setup
  image: alpine:latest
  script:
    - echo "exporting variables..."
    - export $(grep -v '^#' .env.example | xargs -d '\n')
    - echo "variable db_url is : $DB_URL"

