sonar.projectKey=delivery-platform
sonar.projectName=Delivery Platform
sonar.host.url=${SONAR_URL}
sonar.token=${SONAR_TOKEN}

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes